name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ github.job }}-${{ runner.os }}-3.12-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --only main,dev,linter
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files --show-diff-on-failure

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        os: [ubuntu-latest, windows-latest]
    name: Test & Build (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ github.job }}-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          # install the personio-py package together with its test dependencies
          poetry install --with test
      - name: Test with pytest
        run: |
          poetry run pytest tests
      - name: Build a distribution package (sdist & wheel)
        run: |
          poetry build
      - name: Store distribution package
        uses: actions/upload-artifact@v4
        with:
          name: personio-py_${{ matrix.python-version }}_${{ matrix.os }}
          path: dist/
