name: deploy

# will be triggered when a new release is published (draft releases are ignored)
on:
  release:
    types: [published]

jobs:
  release:
    name: Deploy on PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build distribution packages (sdist & wheel)
        run: |
          poetry build
        # publish on PyPI (productive environment)
      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
