name: docs-verify

on:
  pull_request:
    branches:
      - master
    paths:
      # on documentation change (changelog & contribution guidlines are a part of that)
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      # also when docstrings in the source code change
      - 'src/**'

jobs:
  docs:
    name: Generate Sphinx Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ github.job }}-${{ runner.os }}-3.12-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install --only main,docs
      - name: Generate Sphinx Documentation
        run: |
          poetry run make -C docs html SPHINXOPTS="-W --keep-going"
      - uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html/
